# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 73ddfe42b2e3b2531c10f469454c294a634f679baccd8b51b1be6caa3b6deae770e9e376d007709f4b7ae385e52a166adf89b03cc2eceb968a9cdacf78375960

test:
  secret_key_base: c4e4ae725e8ed5bddb02846b2c8577d849c103c0bd7d7ecce8be32a7121ec94ddca10adfdb982e616933e2dbb491c04b6dd781fa190a088a6112ca9ff91afc75

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
