# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
user1 = User.create(username: "Sarah", email: Faker::Internet.email, password: "password")
user2 = User.create(username: "Harry", email: Faker::Internet.email, password: "password")
user3 = User.create(username: "Joe", email: Faker::Internet.email, password: "password")
user4 = User.create(username: "Bob", email: Faker::Internet.email, password: "password")
user5 = User.create(username: "Charlotte", email: Faker::Internet.email, password: "password")
user6 = User.create(username: "Ryan", email: Faker::Internet.email, password: "password")
user7 = User.create(username: "Meg", email: Faker::Internet.email, password: "password")
user8 = User.create(username: "Louise", email: Faker::Internet.email, password: "password")
user9 = User.create(username: "John", email: Faker::Internet.email, password: "password")
user10 = User.create(username: "Ben", email: Faker::Internet.email, password: "password")
user11 = User.create(username: "Ned", email: Faker::Internet.email, password: "password")
user12 = User.create(username: "Mark", email: Faker::Internet.email, password: "password")
user13 = User.create(username: "Rebecca", email: Faker::Internet.email, password: "password")
user14 = User.create(username: "Roberta", email: Faker::Internet.email, password: "password")
user15 = User.create(username: "Cindy", email: Faker::Internet.email, password: "password")
user16 = User.create(username: "Carla", email: Faker::Internet.email, password: "password")
user17 = User.create(username: "Mary", email: Faker::Internet.email, password: "password")
user18 = User.create(username: "Charles", email: Faker::Internet.email, password: "password")
demoUser = User.create(username: "demoUser", email: 'demosareawesome@email.com', password: "demosarecool")

Follow.destroy_all
follow1 = Follow.create(follower_id: user2.id, user_following_id: user1.id)
follow2 = Follow.create(follower_id: user3.id, user_following_id: user6.id)
follow3 = Follow.create(follower_id: user3.id, user_following_id: user4.id)
follow4 = Follow.create(follower_id: demoUser.id, user_following_id: user3.id)
follow5 = Follow.create(follower_id: user3.id, user_following_id: demoUser.id)
follow6 = Follow.create(follower_id: demoUser.id, user_following_id: user2.id)
follow7 = Follow.create(follower_id: user2.id, user_following_id: demoUser.id)
follow8 = Follow.create(follower_id: user5.id, user_following_id: demoUser.id)
follow9 = Follow.create(follower_id: user6.id, user_following_id: demoUser.id)
follow10 = Follow.create(follower_id: user1.id, user_following_id: user11.id)
follow11 = Follow.create(follower_id: user1.id, user_following_id: user15.id)
follow12 = Follow.create(follower_id: user1.id, user_following_id: user12.id)
follow13 = Follow.create(follower_id: user1.id, user_following_id: user18.id)
follow14 = Follow.create(follower_id: user18.id, user_following_id: demoUser.id)
follow15 = Follow.create(follower_id: user17.id, user_following_id: demoUser.id)
follow16 = Follow.create(follower_id: user15.id, user_following_id: demoUser.id)
follow17 = Follow.create(follower_id: user13.id, user_following_id: demoUser.id)
follow18 = Follow.create(follower_id: user1.id, user_following_id: demoUser.id)
follow19 = Follow.create(follower_id: user10.id, user_following_id: demoUser.id)
follow20 = Follow.create(follower_id: user9.id, user_following_id: demoUser.id)
follow21 = Follow.create(follower_id: user8.id, user_following_id: demoUser.id)
